# Generated by Django 5.2.11 on 2026-05-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id_kategorie', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_kategorie', models.CharField(max_length=255)),
                ('popis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id_sklad', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_skladu', models.CharField(max_length=255)),
                ('mesto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id_uzivatel', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=255)),
                ('prijmeni', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Velikosti',
            fields=[
                ('id_velikosti', models.AutoField(primary_key=True, serialize=False)),
                ('eu_velikost', models.IntegerField()),
                ('us_velikost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenisky',
            fields=[
                ('id_tenisky', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_modelu', models.CharField(max_length=255)),
                ('barva', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('rok_vydani', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('mnozstvi', models.IntegerField()),
                ('dostupnost', models.CharField(max_length=10)),
                ('id_kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.kategorie')),
                ('id_sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.sklad')),
                ('id_uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.uzivatel')),
                ('id_velikosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.velikosti')),
            ],
        ),
    ]
