# Generated by Django 5.2.11 on 2026-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenisky',
            name='barva',
            field=models.CharField(choices=[('Černá', 'Černá'), ('Bílá', 'Bílá'), ('Modrá', 'Modrá'), ('Zelená', 'Zelená'), ('Červená', 'Červená'), ('Šedá', 'Šedá'), ('Hnědá', 'Hnědá'), ('Oranžová', 'Oranžová'), ('Žlutá', 'Žlutá')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tenisky',
            name='dostupnost',
            field=models.CharField(choices=[('ANO', 'ANO'), ('NE', 'NE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenisky',
            name='material',
            field=models.CharField(choices=[('Textil', 'Textil'), ('Kůže', 'Kůže'), ('Síťovina', 'Síťovina'), ('Syntetika', 'Syntetika'), ('Recyklovaný materiál', 'Recyklovaný materiál')], max_length=255),
        ),
    ]
