# Generated by Django 5.2.11 on 2026-05-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0002_alter_tenisky_barva_alter_tenisky_dostupnost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet', models.IntegerField(default=1)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('tenisky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.tenisky')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
